Functions and variables names refactor; New sample image; Updated README.md to reflect the changes; Added -c, --check to just check for a new Proton-GE-Custom;

diff --git a/proton-get b/proton-get
--- a/proton-get
+++ b/proton-get
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 #################################################################
 #                                                               #
-#        Proton-GE downloader and installer - proton-get        #
-#                         Version: 2.0.0                        #
+#    Proton-GE-Custom downloader and installer - proton-get     #
+#                         Version: 2.1.0                        #
 #                       Copyright (C) 2021                      #
 #           Marcelo dos Santos Mafra <msmafra@gmail.com>        #
 #       Licensed under the GNU General Public License v3.0      #
@@ -10,7 +10,9 @@
 #           https://gitlab.com/msmafra/proton-get               #
 #                                                               #
 #################################################################
-
+# Disable unicode.
+LC_ALL=C
+LANG=C
 #{{{ Bash settings
 set -o errexit
 set -o errtrace
@@ -18,38 +20,67 @@ set -o nounset
 set -o pipefail
 # set -o xtrace
 #}}}
-# user full name (???) getent passwd $user_name | grep $(id -u) | cut -d ':' -f 5 | cut -d ' ' -f 1
 
+declare ge_proton_title
 declare which_arg
 export PROTONGET_VERSION
 export SCRIPT_FOLDER
 export CURRENT_USER_BIN
 declare -i user_id
 declare user_name
+declare temp_dir
+declare notify_send
+declare exec_xidel
+declare steam_tools_folder
+declare ge_git_url
+declare ge_releases_url
+declare ge_latest_url
+declare ge_proton_file
+declare ge_proton_remote_version
+declare ge_proton_local_version
+declare ge_author
+declare ge_discord_url
 
+ge_proton_title="Proton-GE-Custom"
 which_arg="${1:-}"
-PROTONGET_VERSION="2.0.0"
+PROTONGET_VERSION="2.1.0"
 SCRIPT_FOLDER="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
 CURRENT_USER_BIN="${HOME}/.local/bin"
 user_id="$(id --user)"
 user_name="$(id --user --name)"
+temp_dir="$(mktemp --directory --suffix="${ge_proton_title}" | tee /dev/null 2>&1)"
+notify_send="$(command -v notify-send | tee /dev/null 2>&1)"
+exec_xidel="${HOME}/.local/bin/xidel"
+steam_tools_folder="${HOME}/.local/share/Steam/compatibilitytools.d"
+ge_git_url="https://github.com/GloriousEggroll/proton-ge-custom"
+ge_releases_url="${ge_git_url}/releases"
+ge_latest_url="$("${exec_xidel}" -s "${ge_releases_url}" --xquery '//a/@href[contains(., ".tar.gz")]' | grep "releases" | awk '{printf "%s%s\n","https://github.com", $1}' | head -n 1)"
+ge_proton_file="$(printf "%s" "${ge_latest_url}" | awk -F"/" '{print $9}')"
+ge_proton_remote_version="${ge_proton_file%%.tar*}"
+ge_proton_local_version="$(find "${steam_tools_folder}/" -maxdepth 1 -name '*Proton*' -type d | awk -F"/" '{print $8}' | sort --version-sort --reverse | head --lines=1)"
+ge_author="GloriousEggroll"
+ge_discord_url="https://discord.gg/6y3BdzC"
 
 exit_stage_left() {
 
-    unset which_arg PROTONGET_VERSION SCRIPT_FOLDER CURRENT_USER_BIN xidel_exec raw_file available_version user_id user_name script_mode dry_run temp_dir xidel_url xidel_file exec_xidel steam_tools_folder ge_releases_url ge_latest ge_proton_file ge_proton_remote ge_proton_local
-    printf "\n%s\n" "All done. Bye!"
+    unset -v ge_proton_title which_arg PROTONGET_VERSION SCRIPT_FOLDER CURRENT_USER_BIN user_id user_name temp_dir notify_send exec_xidel steam_tools_folder ge_git_url ge_releases_url ge_latest_url ge_proton_file ge_proton_remote_version ge_proton_local_version ge_author ge_discord_url raw_file available_version script_mode xidel_exec local xidel_url xidel_file ge_count
+    unset -f check_xidel show_version show_usage self_update check_update run_protonget main
+    printf "%s\n" "All done. Bye!"
 
 }
 
 main() {
 
-    trap exit_stage_left EXIT ERR # Elegant exit
-
-    printf "%s: %s\n\n" "-> Argument" "${which_arg:-None}"
+    printf "%s: %s\n" "-> Argument" "${which_arg:-None}"
 
     if [[ "${user_id}" -ne 0 ]];then
 
-        if [[ "${which_arg}" =~ -i|--install|-n|--dryrun ]];then
+        if [[ "${which_arg}" =~ -c|--check ]];then
+
+            check_update
+            exit 0
+
+        elif [[ "${which_arg}" =~ -i|--install|-n|--dryrun ]];then
 
             if [[ "${which_arg}" =~ -n|--dryrun ]];then
 
@@ -81,11 +112,47 @@ main() {
 
     else
 
-        printf "%s\n" "-> Usage of superuser(elevated privileges), is not allowed. Exiting."
+        printf "%s\n" "-> Usage of superuser (elevated privileges), is not allowed. Exiting."
         exit 1
 
     fi
 
+    trap exit_stage_left ERR 0 SIGHUP SIGINT SIGQUIT SIGABRT SIGTERM # Elegant exit
+
+}
+
+check_xidel() {
+
+    local xidel_url
+    local xidel_file
+
+    if [[ ! -f "${exec_xidel}" ]];then
+
+        # Required
+        cd "${temp_dir}" && pwd
+        xidel_url="https://github.com/benibela/xidel/releases/download/Xidel_0.9.8/xidel-0.9.8.linux64.tar.gz"
+        xidel_file="$(printf "%s" "https://github.com/benibela/xidel/releases/download/Xidel_0.9.8/xidel-0.9.8.linux64.tar.gz" | awk -F"/" '{print $9}')"
+
+        printf "%s\n- %s\n- %s\n" "Xidel not found. Info:" "http://www.videlibri.de/xidel.html" "by Benito van der Zander <benito@benibela.de>"
+
+        printf "%s %s\n" "Downloading xidel 0.9.8 (latest stable at 2021-06-28) to a temporary directory" "${temp_dir}"
+        cd "${temp_dir}" && pwd
+        wget --quiet --content-disposition --continue "${xidel_url}"
+
+        printf "\n%s\n" "-> Extracting files to ${temp_dir}"
+        cd "${temp_dir}" && pwd
+        tar --get --file "${xidel_file}" --directory="${temp_dir}"
+
+    elif [[ -f "${HOME}"/.local/bin/xidel ]];then
+
+        printf "%s\n%s%s\n" "-> An installed version of xidel found locally" "-> Using from" "${exec_xidel}"
+
+    else
+
+        exec_xidel="${temp_dir}/xidel"
+        printf "\n-> xidel found. using from %s" "${exec_xidel}"
+
+    fi
 
 }
 
@@ -93,8 +160,7 @@ show_version() {
 
     local xidel_exec
 
-    # printf "%s" "${SCRIPT_FOLDER}"
-    printf "proton-get version %s\n" "${PROTONGET_VERSION}"
+    printf "%s Installed version of proton-get: %s\n\n" "->" "${PROTONGET_VERSION}"
 
     if [[ "$(command -v xidel > /dev/null 2>&1)" ]];then
         xidel_exec="$(command -v xidel > /dev/null 2>&1)"
@@ -105,9 +171,10 @@ show_version() {
 
 show_usage() {
 
-    printf "%s\n" "Proton-GE downloader and installer: proton-get"
+    printf "%s\n" "${ge_proton_title} downloader and installer: proton-get"
     printf "\n%s\n" "Usage: $0 [argument]"
-    printf "\t%s\n" "-i or --install will download and extract Proton-GE"
+    printf "\t%s\n" "-i or --install will download and extract ${ge_proton_title}"
+    printf "\t%s\n" "-c or --check will just check for a new version of ${ge_proton_title}"
     printf "\t%s\n" "-n or --dryrun  will run proton-get without downloading and installing anything"
     printf "\t%s\n" "-u or --update will check and install the latest version of proton-get"
     printf "\t%s\n" "-v or --version will show the current proton-get version"
@@ -148,77 +215,64 @@ self_update() {
 
 }
 
+check_update() {
+
+
+    if [[ "${which_arg}" =~ -c|--check ]];then
+
+        if [[ ! ${ge_proton_remote_version} = "${ge_proton_local_version}" ]];then
+
+            printf "\n-> A new %s release is available: %s \n%s \n" "${ge_proton_title}" "${ge_proton_remote_version}" "${ge_latest_url}"
+
+            if [[ -e "${notify_send}" ]];then
+
+                printf "Available version of proton-get: %s\n" "${ge_proton_remote_version}"
+                "${notify_send}" --urgency=critical "Proton Get" "A new ${ge_proton_title} release is available: ${ge_proton_remote_version}" -i 'dialog-warning'
+                exit 0
+
+            else
+
+                printf "Available version of proton-get: %s\n" "${ge_proton_remote_version}"
+                exit 0
+
+            fi
+
+        else
+
+            printf "No new version available. Your latest installed version %s.\n" "${ge_proton_local_version}"
+            exit 0
+
+        fi
+    fi
+
+}
+
 run_protonget() {
 
-    printf "%s\n%s" "Proton-GE is a modified version of Valve's Proton by GloriousEggroll." "GloriousEggroll's description: Compatibility tool for Steam Play based on Wine and additional components"
-    printf "\n\n%s\n%s" "Check the docs etc in:" "https://github.com/GloriousEggroll/proton-ge-custom"
-    printf "\n\n%s\n%s\n\n" "For Proton-GE issue/bugs reporting contact GloriousEggroll via Discord:" "https://discord.gg/6y3BdzC"
+    local -i ge_count
+    ge_count=5
 
-    local temp_dir
-    local xidel_url
-    local xidel_file
-    local exec_xidel
-    local steam_tools_folder
-    local ge_releases_url
-    local ge_latest
-    local ge_proton_file
-    local ge_proton_remote
-    local ge_proton_local
-
-    # temp_dir="$(mktemp --directory --suffix=ProtonGet > /dev/null 2>&1)"
-    temp_dir="$(mktemp --directory --suffix=ProtonGet)"
-    if [[ ! -f "${HOME}"/.local/bin/xidel ]];then
-
-        # Required
-        cd "${temp_dir}" && pwd
-        xidel_url="https://github.com/benibela/xidel/releases/download/Xidel_0.9.8/xidel-0.9.8.linux64.tar.gz"
-        xidel_file="$(printf "%s" "https://github.com/benibela/xidel/releases/download/Xidel_0.9.8/xidel-0.9.8.linux64.tar.gz" | awk -F"/" '{print $9}')"
-
-        printf "%s\n- %s\n- %s\n" "Xidel not found. Info:" "http://www.videlibri.de/xidel.html" "by Benito van der Zander <benito@benibela.de>"
-
-        printf "%s %s\n" "Downloading xidel 0.9.8 (latest stable at 2021-05-17) to a temporary directory" "${temp_dir}"
-        cd "${temp_dir}" && pwd
-        wget --quiet --content-disposition --continue "${xidel_url}"
-
-        printf "\n%s\n" "-> Extracting files to ${temp_dir}"
-        cd "${temp_dir}" && pwd
-        tar --get --file "${xidel_file}" --directory="${temp_dir}"
-
-    elif [[ -f "${HOME}"/.local/bin/xidel ]];then
-
-        exec_xidel="${HOME}/.local/bin/xidel"
-        printf "%s\n%s%s\n" "-> An installed version of xidel found locally" "-> Using from" "${exec_xidel}"
-
-    else
-
-        exec_xidel="${temp_dir}/xidel"
-        printf "\n-> xidel found. using from %s" "${exec_xidel}"
-
-    fi
-    steam_tools_folder="${HOME}/.local/share/Steam/compatibilitytools.d"
-    ge_releases_url="https://github.com/GloriousEggroll/proton-ge-custom/releases"
-    ge_latest="$("${exec_xidel}" -s "${ge_releases_url}" --xquery '//a/@href[contains(., ".tar.gz")]' | grep "releases" | awk '{printf "%s%s\n","https://github.com", $1}' | head -n 1)"
-    ge_proton_file="$(printf "%s" "${ge_latest}" | awk -F"/" '{print $9}')"
-    ge_proton_remote="${ge_proton_file%%.tar*}"
-    ge_proton_local="$(find "${steam_tools_folder}/" -maxdepth 1 -name '*Proton*' -type d | awk -F"/" '{print $8}' | sort --version-sort --reverse | head --lines=1)"
+    printf "%s is a modified version of Valve's Proton by GloriousEggroll.\n%s" "${ge_proton_title}" "GloriousEggroll's description: Compatibility tool for Steam Play based on Wine and additional components"
+    printf "\nCheck the docs etc at %s." "${ge_git_url}"
+    printf "\nFor %s issues, bugs report to %s via Discord: %s\n"  "${ge_proton_title}" "${ge_author}" "${ge_discord_url}"
 
     # Available ones
-    printf "\n%s\n" "-> Available GE releases (5)"
-    "${exec_xidel}" --silent "${ge_releases_url}" --xquery '//a/@href[contains(., ".tar.gz")]' | grep "releases" | awk '{printf "%s%s\n","https://github.com", $1}' | awk -F"/" '{print $9}' | grep --invert-match "test" | awk -F"." '{print $1"."$2}'
+    printf "\n%s Available %s releases (%s):\n" "->" "${ge_proton_title}" "${ge_count}"
+    # "${exec_xidel}" --silent "${ge_releases_url}" --xquery '//a/@href[contains(., ".tar.gz")]' | grep "releases" | awk '{printf "%s%s\n","https://github.com", $1}' | awk -F"/" '{print $9}' | grep --invert-match "test" | awk -F"." '{print $1"."$2}'
+    "${exec_xidel}" --silent "${ge_releases_url}" --xquery '//a/@href[contains(., ".tar.gz")]' | grep "releases" | awk '{printf "%s%s\n","https://github.com", $1}' | awk -F"/" '{print $9}' | grep --invert-match "test" | awk -F"." '{printf "\t%s.%s\n",$1,$2}'
 
     # Current installed ones
-    printf "\n-> %s\n" "Installed GE releases"
-    find "${steam_tools_folder}/" -maxdepth 1 -name '*Proton*' -type d | awk -F"/" '{print $8}' | sort --version-sort --reverse
+    printf "\n-> Installed %s releases:\n" "${ge_proton_title}"
+    find "${steam_tools_folder}/" -maxdepth 1 -name '*Proton*' -type d | awk -F"/" '{printf "\t%s\n",$8}' | sort --version-sort --reverse
 
     # Check if is already installed before download
-    cd "${temp_dir}" && pwd
-    if [[ ! ${ge_proton_remote} = "${ge_proton_local}" ]];then
+    if [[ ! ${ge_proton_remote_version} = "${ge_proton_local_version}" ]];then
+        cd "${temp_dir}" && pwd
 
-        printf "\n%s %s \n%s \n" "-> A new GE release is available:" "${ge_proton_remote}" "${ge_latest}"
-
-        printf "\n%s \n%s %s\n" "-> Downloading using:" "wget --quiet --show-progress --progress=bar --content-disposition --continue " "${ge_latest}"
+        printf "\n%s A new %s release is available: %s \n%s \n" "->" "${ge_proton_title}" "${ge_proton_remote_version}" "${ge_latest_url}"
+        printf "\n%s \n%s %s\n" "-> Downloading using:" "wget --quiet --show-progress --progress=bar --content-disposition --continue " "${ge_latest_url}"
         if [[ ! "${which_arg}" =~ -n|--dryrun ]];then
-            wget --quiet --show-progress --progress=bar --content-disposition --continue "${ge_latest}"
+            wget --quiet --show-progress --progress=bar --content-disposition --continue "${ge_latest_url}"
         fi
 
         printf "\n-> Extracting using:\ntar --get --file %s --directory=%s\n" "${ge_proton_file}" "${steam_tools_folder}"
