proton-get checks if is being ran by root; Checks for the existance of $HOME/.local/bin; Messages of what is being done are clearer now; setup.sh create $HOME/.local/bin if it doesn't exist; Checks for the existance of xidel;

diff --git a/proton-get b/proton-get
--- a/proton-get
+++ b/proton-get
@@ -52,83 +52,96 @@ exit_stage_left() {
 }
 
 protonGet() {
-    local temp_dir
-    local xidel_url
-    local xidel_file
-    local exec_xidel
-    local steam_tools_folder
-    local ge_releases_url
-    local ge_latest
-    local ge_proton_file
-    local ge_proton_remote
-    local ge_proton_local
 
-    temp_dir="$(mktemp --directory --suffix=ProtonGet)"
+    local -i user_id
+    user_id="$(id --user)"
 
-    if [[ ! -f "${HOME}"/.local/bin/xidel ]];then
+    if [[ "${user_id}" -ne 0 ]];then
 
-        # Required
+        local temp_dir
+        local xidel_url
+        local xidel_file
+        local exec_xidel
+        local steam_tools_folder
+        local ge_releases_url
+        local ge_latest
+        local ge_proton_file
+        local ge_proton_remote
+        local ge_proton_local
+
+        temp_dir="$(mktemp --directory --suffix=ProtonGet)"
+
+        if [[ ! -f "${HOME}"/.local/bin/xidel ]];then
+
+            # Required
+            cd "${temp_dir}" && pwd
+            xidel_url="https://github.com/benibela/xidel/releases/download/Xidel_0.9.8/xidel-0.9.8.linux64.tar.gz"
+            xidel_file="$(printf "%s" "https://github.com/benibela/xidel/releases/download/Xidel_0.9.8/xidel-0.9.8.linux64.tar.gz" | awk -F"/" '{print $9}')"
+
+            printf "%s\n- %s\n- %s\n" "Xidel not found. Info:" "http://www.videlibri.de/xidel.html" "by Benito van der Zander <benito@benibela.de>"
+
+            printf "%s %s\n" "Downloading xidel 0.9.8 (latest stable at 2021-05-17) to the temporary directory" "${temp_dir}"
+            cd "${temp_dir}" && pwd
+            wget --quiet --content-disposition --continue "${xidel_url}"
+
+            printf "\n%s\n" "-> Extracting files to ${temp_dir}:"
+            cd "${temp_dir}" && pwd
+            tar --get --verbose --file "${xidel_file}" --directory="${temp_dir}"
+
+        fi
+
+        if [[ -f "${HOME}"/.local/bin/xidel ]];then
+
+            exec_xidel="${HOME}/.local/bin/xidel"
+            printf "\n-> xidel found. using from %s" "${exec_xidel}"
+
+        else
+
+            exec_xidel="${temp_dir}/xidel"
+            printf "\n-> xidel found. using from %s" "${exec_xidel}"
+
+        fi
+        steam_tools_folder="${HOME}/.local/share/Steam/compatibilitytools.d"
+        ge_releases_url="https://github.com/GloriousEggroll/proton-ge-custom/releases"
+        ge_latest="$("${exec_xidel}" -s "${ge_releases_url}" --xquery '//a/@href[contains(., ".tar.gz")]' | grep "releases" | awk '{printf "%s%s\n","https://github.com", $1}' | head -n 1)"
+        ge_proton_file="$(printf "%s" "${ge_latest}" | awk -F"/" '{print $9}')"
+        ge_proton_remote="${ge_proton_file%%.tar*}"
+        ge_proton_local="$(find "${steam_tools_folder}/" -maxdepth 1 -name "*Proton*" -type d | awk -F"/" '{print $8}' | sort --reverse | head --lines=1)"
+
+        # Available ones:
+        printf "\n-> %s\n" "Available GE releases:"
+        "${exec_xidel}" --silent "${ge_releases_url}" --xquery '//a/@href[contains(., ".tar.gz")]' |
+        grep "releases" | awk '{printf "%s%s\n","https://github.com", $1}'
+
+        # Current installed ones:
+        printf "\n-> %s\n" "Installed GE releases:"
+        find "${HOME}"/.local/share/Steam/compatibilitytools.d/ -maxdepth 1 -name "*Proton*" -type d | awk -F"/" '{print $8}' | sort --reverse
+
         cd "${temp_dir}" && pwd
-        xidel_url="https://github.com/benibela/xidel/releases/download/Xidel_0.9.8/xidel-0.9.8.linux64.tar.gz"
-        xidel_file="$(printf "%s" "https://github.com/benibela/xidel/releases/download/Xidel_0.9.8/xidel-0.9.8.linux64.tar.gz" | awk -F"/" '{print $9}')"
+        # Check if is already installed before download
+        if [[ ! ${ge_proton_remote} = "${ge_proton_local}" ]];then
 
-        printf "%s\n- %s\n- %s\n" "Xidel not found. Info:" "http://www.videlibri.de/xidel.html" "by Benito van der Zander <benito@benibela.de>"
+            printf "\n-> A new GE release is available: %s \n%s \n" "${ge_proton_remote}" "${ge_latest}"
 
-        printf "%s %s\n" "Downloading xidel 0.9.8 (latest stable at 2021-05-17) to the temporary directory" "${temp_dir}"
-        cd "${temp_dir}" && pwd
-        wget --quiet --content-disposition --continue "${xidel_url}"
+            printf "\n-> Downloading using:\nwget --quiet --show-progress --progress=bar --content-disposition --continue %s\n" "${ge_latest}"
+            wget --quiet --show-progress --progress=bar --content-disposition --continue "${ge_latest}"
 
-        printf "\n%s\n" "-> Extracting files to ${temp_dir}:"
-        cd "${temp_dir}" && pwd
-        tar --get --verbose --file "${xidel_file}" --directory="${temp_dir}"
+            printf "\n-> Extracting using:\ntar --get --verbose --file %s --directory=%s\n" "${ge_proton_file}" "${steam_tools_folder}"
+            tar --get --verbose --file "${ge_proton_file}" --directory="${steam_tools_folder}"
 
-    fi
+            printf "\n%s was extracted/installed in %s\n" "-> ${ge_proton_file}" "${steam_tools_folder}"
+            printf "\n-> All files were downloaded to the temporary folder %s\n" "${temp_dir}"
 
-    if [[ -f "${HOME}"/.local/bin/xidel ]];then
+        else
 
-        exec_xidel="${HOME}/.local/bin/xidel"
-        printf "\n-> xidel found. using from %s" "${exec_xidel}"
+            printf "\n%s is already installed\n" "${ge_proton_file}"
+
+        fi
 
     else
 
-        exec_xidel="${temp_dir}/xidel"
-        printf "\n-> xidel found. using from %s" "${exec_xidel}"
-
-    fi
-    steam_tools_folder="${HOME}/.local/share/Steam/compatibilitytools.d"
-    ge_releases_url="https://github.com/GloriousEggroll/proton-ge-custom/releases"
-    ge_latest="$("${exec_xidel}" -s "${ge_releases_url}" --xquery '//a/@href[contains(., ".tar.gz")]' | grep "releases" | awk '{printf "%s%s\n","https://github.com", $1}' | head -n 1)"
-    ge_proton_file="$(printf "%s" "${ge_latest}" | awk -F"/" '{print $9}')"
-    ge_proton_remote="${ge_proton_file%%.tar*}"
-    ge_proton_local="$(find "${steam_tools_folder}/" -maxdepth 1 -name "*Proton*" -type d | awk -F"/" '{print $8}' | sort --reverse | head --lines=1)"
-
-    # Available ones:
-    printf "\n-> %s\n" "Available GE releases:"
-    "${exec_xidel}" --silent "${ge_releases_url}" --xquery '//a/@href[contains(., ".tar.gz")]' |
-    grep "releases" | awk '{printf "%s%s\n","https://github.com", $1}'
-
-    # Current installed ones:
-    printf "\n-> %s\n" "Installed GE releases:"
-    find "${HOME}"/.local/share/Steam/compatibilitytools.d/ -maxdepth 1 -name "*Proton*" -type d | awk -F"/" '{print $8}' | sort --reverse
-
-    cd "${temp_dir}" && pwd
-    # Check if is already installed before download
-    if [[ ! ${ge_proton_remote} = "${ge_proton_local}" ]];then
-
-        printf "\n-> A new GE release is available: %s \n%s \n" "${ge_proton_remote}" "${ge_latest}"
-
-        printf "\n-> Downloading using:\nwget --quiet --show-progress --progress=bar --content-disposition --continue %s\n" "${ge_latest}"
-        wget --quiet --show-progress --progress=bar --content-disposition --continue "${ge_latest}"
-
-        printf "\n-> Extracting using:\ntar --get --verbose --file %s --directory=%s\n" "${ge_proton_file}" "${steam_tools_folder}"
-        tar --get --verbose --file "${ge_proton_file}" --directory="${steam_tools_folder}"
-
-        printf "\n%s was extracted/installed in %s\n" "-> ${ge_proton_file}" "${steam_tools_folder}"
-        printf "\n-> All files were downloaded to the temporary folder %s\n" "${temp_dir}"
-
-    else
-
-        printf "\n%s is already installed\n" "${ge_proton_file}"
+        printf "%s\n" "-> Usage of superuser/elevated privileges, is not allowed. Exiting <-"
+        exit 1
 
     fi
 
